language: java
jdk:
  - openjdk8
  - openjdk11

after_success:
  - mvn clean install -Dpmd.skip=true -Dcheckstyle.skip=true -Dmaven.test.skip=true
  - mvn cobertura:cobertura coveralls:report


cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/